name: "Draft Release"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_release:
    name: Build and Release Android APK
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for changelog generation

      - name: ⚙️ Setup Java Environments
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
          cache: true

      - name: 📦 Get Dependencies
        run: flutter pub get

      - name: 🛠️ Build APK
        run: flutter build apk --release

      - name: 🏷️ Draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }} — Release
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
